### ISSUE TITLE
Visit and Learn

### ISSUE THREAD

**Issue by gugek** [chfm/chfm-website#1]
Migrate visit and learn section from http://chapelhillfriends.org/NewToFriends.html

**Comment by radiolevity** [comment]
About page now in working order. It's not pretty, and some of the links are not there (I only included the ones that have existing destinations), but it's better than the scrollspy-mess that existed before!

commit: about page in usable state

**Comment by radiolevity** [comment]
About page renamed and buttons now wrap text on mobile.

**Comment by radiolevity** [comment]
Whoops! Not all links set up properly; reopening until all the content is either Officially Removed™ or it's added.

**Comment by gugek** [comment]
Very good; closing this.
