### ISSUE TITLE
Quakerism 101 Page

### ISSUE THREAD

**Issue by radiolevity** [chfm/chfm-website#12]
Jan asked us to add this to the site. I added it to the navbar but the actual page needs to be made. @gugek it looks like you made the current one? If so it shouldn't be too difficult to move the bootstrap stuff over into one of the Jekyll templates we have now.

**Comment by radiolevity** [comment]
Okay, the page is added and filled in, although I just copied and pasted in the `<ul>/<li>` list from the existing page, as well as wrapped them in an accordion. @gugek the pdfs still need to be linked properly. Do you have all of the files somewhere sorted already?

**Comment by radiolevity** [comment]
@gugek incorporate markdown files from q101 repo

**Comment by gugek** [comment]
Removed data file and coded mixed HTML and markdown into a separate subdirectory ~Q101~ a3a690c

**Comment by gugek** [comment]
Some issue in handling responsive video embeds that aren't in YT
