### ISSUE TITLE
Calendar entries don't display on desktop

### ISSUE THREAD

**Issue by gugek** [chfm/chfm-website#19]
https://chfm.github.io/chfm-website/calendar shows an empty calendar on MacOS Safari.

**Comment by radiolevity** [comment]
I tried it and it works... what exactly were you testing? The site was live, right?

**Comment by gugek** [comment]
Chrome it works fine.

UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

Safari on OS X doesn't have anything in the events or agenda view

![image](https://user-images.githubusercontent.com/223778/51582719-549f4900-1e9b-11e9-8035-b987b9117671.png)

UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15

**Comment by gugek** [comment]
So resetting browser cache/cookies for that host seemed to work ... seems odd that a force refresh won't fix it.
