### ISSUE TITLE
Meeting for Worship With Attention to Business

### ISSUE THREAD

**Issue by gugek** [chfm/chfm-website#20]
Add page to support business meeting.

- PDFs in `assets\MWAB\pdf\`
- Content in a data-yml file
- template in `mwab.html` page.

**Comment by radiolevity** [comment]
Done. Workflow for updating:

1. upload current pdfs to assets/mwab/
2. update titles and pdf links on _data/mwab.yml
3. update "Agenda" link on mwab.md
