### ISSUE TITLE
Newsletter Page

### ISSUE THREAD

**Issue by radiolevity** [chfm/chfm-website#6]
Should we try to implement the newsletter archive in a different format to the current one? Even if not, the old newsletters need to be added to the new site.

**Comment by gugek** [comment]
I'd like to have some sort of browseable archive.  With the current newsletter either on its own page or prominent on the archive page.

**Comment by gugek** [comment]
Ok I added the structure and the templating for the newsletter page. 

I don't know the bootstrap stuff so if you can run from ad453c030a462258168b70fc83b5f8ae091ee08d

The workflow for whoever is adding newsletters.

- name the newsletter pdf file in the specific format `newsletter-yyyy-mm.pdf`: example `newsletter-2017-02.pdf`
- put the pdf file in the `/assets/nl/yyyy` folder: example `/assets/nl/2018` for newsletters published in 2018.
- add to `_config.yml` the appropriate year and its variables in the defaults

The template should generate the appropriate groups and links

@radiolevity: going to pass this on to you with the existing template.

**Comment by radiolevity** [comment]
Page structure updated using your code, I think it's in a presentable state at this point.
