### ISSUE TITLE
Donation Page

### ISSUE THREAD

**Issue by radiolevity** [chfm/chfm-website#9]
There are... multiple issues with the Donations page. I've added it but having Paypal functionality might be nice (just for some added security and/or trustworthiness), maybe Apple Pay and Android Wallet as well, just to make mobile donations easier. Admittedly, that would be more of an exercise for me than an actual issue to be solved. One way or another, the links need to be added properly. Maybe find an alternative to the existing pdfs?

**Comment by gugek** [comment]
Reuse the existing assets and links. Go ahead and get what you ahve in there for now.

**Comment by radiolevity** [comment]
PDFs added to new assets folder. Links fixed.
